[package]
name = "argon2-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
clap = { version = "4.5.54", features = ["derive"] }
hex = "0.4.3"

[dev-dependencies]
rand = { version = "0.9.2", features = ["std", "std_rng"] }
